### PR TITLE
build: Update CRDs and k8s dependencies

### PR DESCRIPTION
**Pull request by colunira**
CRDs in version v1beta1 are deprecated. Update the version to v1 and bump k8s dependencies.

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! Could you look into the failing test cases please? :)

**Comment by colunira** [comment]
Sure, I'm working on this in parallel with other tasks, so it may take a moment or two ;)

**Comment by colunira** [comment]
@aeneasr PR is ready for review :)

**Review by Demonsthere — APPROVED** [review]
LGTM :)

**Comment by aeneasr** [comment]
https://github.com/ory/hydra-maester/pull/68#issuecomment-833548524

looks like it wasn't regenerated yet?

**Comment by Demonsthere** [comment]
> [#68 (comment)](https://github.com/ory/hydra-maester/pull/68#issuecomment-833548524)
> 
> looks like it wasn't regenerated yet?
They are, during review we saw some changes, but traced them to a version mismatch of kubebuilder. The CRD in this PR is consistent with kubernetes 1.20. 
We need to remember to include the new CRD in charts after this PR has been merged

**Pull request merged**
