### PR TITLE
feat: implement handling token lifespans

### PR DESCRIPTION
**Pull request by David-Wobrock**
Allow setting various Hydra OAuth2 client token lifespans through hydra-maester.

## Related Issue or Design Document

Fixes https://github.com/ory/hydra-maester/issues/112

Relates to https://github.com/ory/k8s/pull/691

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md) and signed the CLA.
- [ ] I have referenced an issue containing the design document if my change introduces a new feature.
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security vulnerability. 
      If this pull request addresses a security vulnerability, 
      I confirm that I got approval (please contact [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push the changes.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] I have added the necessary documentation within the code base (if appropriate).

### CODE REVIEW

**Review by Demonsthere — COMMENTED** [review]
Please update the branch, and take a look at the tests, i see they are failing with unexpected errors

**Comment by David-Wobrock** [comment]
> Please update the branch, and take a look at the tests, i see they are failing with unexpected errors

Thanks, I updated the branch.

The Docker image scan is failing because of CVEs is older Golang versions.
I guess we can fix that in a next patch :)

**Comment by Demonsthere** [comment]
> > Please update the branch, and take a look at the tests, i see they are failing with unexpected errors
> 
> Thanks, I updated the branch.
> 
> The Docker image scan is failing because of CVEs is older Golang versions. I guess we can fix that in a next patch :)

I have updated the internal for golang 1.22 and k8s, please see https://github.com/ory/hydra-maester/pull/147 and rebase ;)

**Comment by David-Wobrock** [comment]
Thanks @Demonsthere 

Rebased and pushed the updated branch.

**Review by Demonsthere — APPROVED** [review]

**Pull request merged**
