### PR TITLE
feat: Add a namespace filter option

### LINKED ISSUE #55: Multiple deployments cause problems
It appears that it is not currently possible to run multiple deployments of hydra-maester at the same time in different namespaces. The problem appears to be that all hydra-maester instances look for all oauth2client instances regardless of namespaces. It seems like like this could be resolved by allowing an optional setting for namespaces under management and then all clients outside of those namespaces would be ignored.

Maybe I'm being ignorant and there is a way to handle this without code changes, but I can't seem to figure out how.

If I'm right and a code change is required I'm happy to do the work I just need to know if @aeneasr thinks it would be better to make the filter a Predicate added to the manager in the SetupWithManager method, as a check in the Reconcile method or some other mechanism I've yet to think of.

### PR DESCRIPTION
**Pull request by jhutchins**
Fixes #55

### CODE REVIEW

**Comment by aeneasr** [comment]
Thank you! Would it be possible to add a test for this as well?

**Comment by greenboxal** [comment]
I still get RBAC errors when removing all Cluster level roles as it tries to list all Secrets in the cluster. Fix seems to be passing `Namespace` on `ctrl.NewManager`, but unfortunately this doesn't seem to support multiple namespaces.

**Comment by greenboxal** [comment]
Maybe the idea of the PR was not to optionally get rid of Cluster-level roles, but I'd think that's also an important feature. Maybe we could have an `--only-namespace` flag?

Happy to contribute as well.

**Comment by aeneasr** [comment]
I have to admit that I'm out of my element here. Maybe you could explain it a bit more? What would `--only-namespace` do?

**Comment by greenboxal** [comment]
This might be the wrong way of solving this use case:

* I want `hydra-maester` to run on _some_ namespaces
* I don't want **any** Cluster-wide rules

Currently, even when using the flag added by this PR, the controller will try to cache all `Secret` objects, resulting in it running a `List` operation on the entire cluster (requires ClusterRole).

The way I found to stop it from doing so is passing `Namespace` to `manager.New()`, but unfortunately it seems to only accept a single namespace, hence the `--only-namespace` suggestion.

But at the end of the day, I just want to get rid of Cluster-wide permissions on secrets as that's a security issue.

**Comment by aeneasr** [comment]
`manager.New()` is a Kubernetes API?

**Comment by greenboxal** [comment]
@aeneasr Sorry, wrong name, I meant `ctrl.NewManager` (https://github.com/ory/hydra-maester/blob/master/main.go#L75)

**Comment by aeneasr** [comment]
I see - so the problem is that the Kubernetes Manager watches all Secrets/ConfigMaps from all namespaces in order to cache them? As far as I can tell, the `Options.Namespace` key only controls that setting:

>  // Namespace if specified restricts the manager's cache to watch objects in
    // the desired namespace Defaults to all namespaces
    //
    // Note: If a namespace is specified, controllers can still Watch for a
    // cluster-scoped resource (e.g Node).  For namespaced resources the cache
    // will only hold objects from the desired namespace.

If my understanding is correct, we could scope the namespace for the secrets on the secret level?

**Comment by greenboxal** [comment]
I'm not sure why it watches for those Secrets/ConfigMaps, it could be for leader election (AFAIK it uses a configmap or secret as a locking mechanism), or because `hydra-maester` tries to read Secrets, and so the default behavior for the k8s client library is to cache.

In any case, I believe that as far as we can set that option we would be able to remove ClusterRoles for those who want that. Maybe we could call the flag `--controller-namespace` and document appropriately? I can push another PR if that makes sense so the OP doesn't have to worry about it.

**Comment by aeneasr** [comment]
Yup that sounds good to me and sorry for the late reply!

**Comment by aeneasr** [comment]
Closing due to inactivity

**Pull request closed without merging**
